language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.0
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration
